### ISSUE TITLE
Best way to enrich with my own requirements?

### ISSUE THREAD

**Issue by RooieRakkert** [okwrtdsh/anaconda3#2]
I'm in love with your level-based approach for these Dockers! Great job and thanks for sharing!
However, what would you recommend as the favorable approach to enrich them with my own requirements/dependencies?

For example, if I'd like to run Keras on my GPU, with some new dependencies which are not currently present in your base image..
Would you recommend to create a new Dockerfile, build `FROM keras-10.0-cudnn7` as base image, add my dependencies here?

Or, should I change your base `10.0-cudnn7` Dockerfile and insert my own dependencies, then build everything from scratch?

**Comment by okwrtdsh** [comment]
@RooieRakkert 
Thanks for your comment!

I prefer to add at run time when I have few requirements.

On the other hand, when I have many (or large) requirements or I need build something to add them, I often create a new Docker Image. (In this case, the purpose of Docker Image often changes.)

When requirements are depended on keras, I select `keras-XXX-cudnnX` as base image.
When they are needed to build keras, I select `tf-XXX-cudnnX` or `XXX-cudnnX`as base image.

I'm sorry for my broken English...

**Comment by RooieRakkert** [comment]
Cheers, thanks! I'll go for the second option, creating a new Docker image based on the latest image, updated with additional required dependencies.
